<?php
 return array (
  'DB_TYPE' => 'mysql',
  'DB_HOST' => 'localhost',
  'DB_NAME' => 'sz',
  'DB_USER' => 'root',
  'DB_PWD' => '',
  'DB_PORT' => 3306,
  'DB_PREFIX' => 'sc_',
  'SY_TITLE' => '网站标题',
  'SY_KEYS' => '网站关键字',
  'SY_EMAIL' => 'szsany@126.com ',
  'SY_RECORD' => ' 粤ICP备12084928-1号',
  'SY_COPYRIGHT' => 'Copyright © 2004-2017 深圳市三一精工科技有限公司 版权所有',
  'SY_DESC' => '深圳市三一精工科技有限公司专业生产：开关电源、电源适配器、安防电源等产品，价格优惠、性能稳定，欢迎新老客户来电选购。',
  'SY_ADDRESS' => '深圳市龙岗区吉祥南路1号宝力大厦二楼',
  'SY_MILL_ADDRESS' => '惠州市惠阳经济开区十美路盈丰工业园',
  'SY_PHONE' => '13428986787',
  'SY_QQ' => '154007515',
  'TAGS' => 'php,Html/CSS,Mysql,Html5,JQuery,JavaScript,Bootstrap,CSS3,前端工具,大数据,Thinkphp,Ajax,Curl,表单,JSON,手机,后台,插件',
  'BQY' => '滚动,幻灯片,轮播,焦点图,弹出层,滑动,切换,菜单,抽奖,导航菜单,广告,动画,导航,上传,缩略图,旋转,全屏,下拉菜单,瀑布流,统计图,bootstrap,表单,分页,手风琴,3d,遮罩层,垂直,select,rotate,加载,响应式,qq,提示下拉,画廊,日期,页面,二级菜单,Slide,时间轴,相册,拖动,悬浮,鼠标,柱状图,upload,菜单导航,放大,转盘,购物车,图表,验证,放大镜,下拉框,美化,图片,ajax,时间,编辑器,scroll,选项卡,懒加载,视频,倒计时,table,表格,音频,排序,modal,水平,lottery,翻牌,canvas,星星,裁剪,cookie,日历选择a,nimate,联动,定位,tab,照片墙树,淘宝,背景,fullpage,邮箱,page,多级菜单,手机菜单,阴影,formaccordion,缩小,地图,在线,投票,登录,顶部,手机,头像,无限,验证码,测试',
  'DB_CHARSET' => 'utf8',
  'DB_DEBUG' => true,
  'REG' => 20,
  'LOGIN' => 5,
  'COMMENT' => 5,
  'TOPIC' => 6,
  'DELETECOMMENT' => 10,
  'DELETETOPIC' => 12,
  'AUTO_LOGIN_KEY' => '1096728445',
  'AUTO_LOGIN_TIME' => 1209600,
  'CHECK_EMAIL' => 30,
  'FACE' => 7,
  'RELEASE' => 8,
  'ADMIN_ID' => 8,
); ?>